AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM user and policies for CI/CD deployment'

Parameters:
  ProjectName:
    Type: String
    Description: 'Name of the project'

Resources:
  CICDUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${ProjectName}-cicd-user"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: CI-CD
        - Key: ManagedBy
          Value: CloudFormation

  CICDDeploymentPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${ProjectName}-cicd-deployment-policy"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: S3BucketAccess
            Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetBucketLocation
              - s3:GetBucketVersioning
            Resource:
              - !Sub 
                - "arn:aws:s3:::${StagingBucket}"
                - StagingBucket: !ImportValue 
                    Fn::Sub: "${ProjectName}-staging-BucketName"
              - !Sub 
                - "arn:aws:s3:::${ProdBucket}"
                - ProdBucket: !ImportValue 
                    Fn::Sub: "${ProjectName}-prod-BucketName"
          - Sid: S3ObjectAccess
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:PutObjectAcl
            Resource:
              - !Sub 
                - "arn:aws:s3:::${StagingBucket}/*"
                - StagingBucket: !ImportValue 
                    Fn::Sub: "${ProjectName}-staging-BucketName"
              - !Sub 
                - "arn:aws:s3:::${ProdBucket}/*"
                - ProdBucket: !ImportValue 
                    Fn::Sub: "${ProjectName}-prod-BucketName"
          - Sid: CloudFrontInvalidation
            Effect: Allow
            Action:
              - cloudfront:CreateInvalidation
              - cloudfront:GetInvalidation
              - cloudfront:ListInvalidations
            Resource: "*"
      Users:
        - !Ref CICDUser

Outputs:
  CICDUserName:
    Description: 'Name of the CI/CD IAM user'
    Value: !Ref CICDUser
    Export:
      Name: !Sub "${AWS::StackName}-CICDUserName"
      
  CICDUserArn:
    Description: 'ARN of the CI/CD IAM user'
    Value: !GetAtt CICDUser.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CICDUserArn"
      
  StagingBucket:
    Description: 'Staging S3 bucket name'
    Value: !Sub "${ProjectName}-staging-static-content"
      
  ProductionBucket:
    Description: 'Production S3 bucket name'
    Value: !Sub "${ProjectName}-prod-static-content"